# Generated by Django 5.0.4 on 2024-04-09 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Topiiic',
        ),
    ]
